-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgnItC3bPy0VkD99dp
ehrjQfHcUlKu1fTiIsgMzaA74pagCgYIKoZIzj0DAQehRANCAARLdVRjFm42zOfr
7HZkzw5kWzgWxeUWiGvTC3DgwOgxjoghBUYNHZ7mZJ1ksq7gP4oozQmd3xVAhbkp
/toVYCay
-----END PRIVATE KEY-----